In [26]:
from tokenizers import Tokenizer, models, trainers
from tokenizers.pre_tokenizers import Whitespace


# Create a SentencePiece model
model = models.WordLevel()

# Initialize a tokenizer with special tokens [SOS] and [EOS]
tokenizer = Tokenizer(model)
tokenizer.pre_tokenizer = Whitespace()
# tokenizer.add_tokens(["[SOS]", "[EOS]"])

# Train the tokenizer (you need to provide your training data)
training_data = ["This is an example sentence."]
trainer = trainers.WordLevelTrainer(special_tokens=["[PAD]", "[UNK]", "[SOS]", "[EOS]"])
tokenizer.train_from_iterator(training_data, trainer)

print(tokenizer.padding)
# tokenizer.enable_padding(pad_token='[PAD]', length=20)
# Tokenize your input text
input_text = "[SOS] This is an example sentence. [EOS]"
output = tokenizer.encode(input_text, add_special_tokens=False)  # Set add_special_tokens to True
print(output)
# Access the token IDs
output.pad(pad_token='[PAD]', length=20)
token_ids = output.ids
print("Token IDs:", token_ids, len(token_ids))
print(tokenizer.decode(token_ids), )
# print(tokenizer.padding)
# print(output.attention_mask)

# tokenizer.padding = 
output = tokenizer.encode(input_text, add_special_tokens=False)  # Set add_special_tokens to True

# Access the token IDs
token_ids = output.ids
print("Token IDs:", token_ids, len(token_ids))


None
Encoding(num_tokens=8, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])
Token IDs: [2, 5, 8, 6, 7, 9, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 20
This is an example sentence .
Token IDs: [2, 5, 8, 6, 7, 9, 4, 3] 8


In [27]:
tokenizer.token_to_id('[SOS]')

2

In [21]:
# print(tokenizer.to_str(True))
tokenizer.token_to_id('[SOS]')

5

In [10]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers, processors

# Create a WordLevel model with WhiteSpace pre-tokenizer
model = models.WordLevel()
pre_tokenizer = pre_tokenizers.Whitespace()

# Initialize a tokenizer
tokenizer = Tokenizer(model)
tokenizer.pre_tokenizer = pre_tokenizer

# Train the tokenizer (you need to provide your training data)
training_data = ["This is an example sentence."]
trainer = trainers.WordLevelTrainer(special_tokens=["[PAD]", "[CLS]", "[SEP]", "[MASK]", "[UNK]"])
tokenizer.train_from_iterator(training_data, trainer)

# Tokenize your input text
input_text = "This is an example sentence."
output = tokenizer.encode(input_text, add_special_tokens=True)

# Access the token IDs
token_ids = output.ids
print("Token IDs:", token_ids)


Token IDs: [6, 9, 7, 8, 10, 5]


In [28]:
import torch

# Create a square matrix
matrix = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Use torch.triu to extract the upper triangular part
upper_triangular = torch.triu(matrix)

print("Original Matrix:")
print(matrix)

print("\nUpper Triangular Matrix:")
print(upper_triangular)

size=3
torch.triu(torch.ones(1,size,size), diagonal=1)

Original Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Upper Triangular Matrix:
tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])


tensor([[[0., 1., 1.],
         [0., 0., 1.],
         [0., 0., 0.]]])

In [35]:
one = torch.ones(1,size,size)
torch.triu(one, diagonal=1)==0
# return mask!=0

tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]]])

In [31]:
one

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
import torch
torch.empty(1,1).fill_(1)

tensor([[1.]])

In [22]:
torch.tensor([[[1], [2]]])

tensor([[[1],
         [2]]])

In [1]:
import yaml
from pathlib import Path

config = yaml.safe_load('config.yml')
model_folder = f"{config['model_folder']}"
model_filename = f"{config['model_basename']}*"
weights_files = list(Path(model_folder).glob(model_filename))

TypeError: string indices must be integers

In [ ]:
weights_files, 